### PR TITLE
add new supported networks

### PR DESCRIPTION
**Pull request by dhruv-chauhan**

### CODE REVIEW

**Comment by dhruv-chauhan** [comment]
requesting review @steegecs

**Review by steegecs — COMMENTED** [review]
Why remove metis and scroll?

**Comment by dhruv-chauhan** [comment]
Did not remove them, they're still in the list. Rebased incorrectly creating copies, had to remove the repeated ones.

**Comment by melotik** [comment]
Oops, I fixed this in a separate PR lol

**Pull request closed without merging**
